version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - gosec
    - misspell
    - staticcheck
    - revive

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - go-starter
